### ISSUE TITLE
undefined method `body' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by shyamperi** [openc/turbot-client#15] opened 2014-12-28 10:52 UTC
Error:       undefined method `body' for nil:NilClass (NoMethodError)
    Backtrace:   /usr/local/lib/ruby/gems/2.2.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:142:in `initialize'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:114:in `new'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:114:in `rescue in request'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:106:in `request'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:54:in `create_draft_data'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/lib/turbot/command/bots.rb:428:in `submit_batch'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/lib/turbot/command/bots.rb:424:in `handle_valid_record'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:24:in `process'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-runner-0.1.14/lib/turbot_runner/script_runner.rb:55:in `run'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:72:in `run_script'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:20:in `run'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/lib/turbot/command/bots.rb:288:in `preview'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/lib/turbot/command.rb:219:in `run'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/lib/turbot/cli.rb:28:in `start'
                 /usr/local/lib/ruby/gems/2.2.0/gems/turbot-0.1.9/bin/turbot:17:in `<top (required)>'
                 /usr/local/bin/turbot:23:in `load'
                 /usr/local/bin/turbot:23:in `<main>'

    Command:     turbot bots:preview
    Version:     turbot-gem/0.1.9 (x86_64-darwin14) ruby/2.2.0

**Comment by sebbacon** [comment] 2015-01-12 09:40
Have you any notes about how to reproduce this? Link to the bot in question?

**Comment by shyamperi** [comment] 2015-01-12 10:59
Sorry @sebbacon not able to reproduce may be it is a one time network / server related.

**Comment by jpmckinney** [comment] 2015-11-11 13:24
Closing since not reproducible.

**Closed by jpmckinney** 2015-11-11 13:24 UTC
